### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by pyanodon** [pyanodon/pYCoalprocesing#23]
Hello,  after the merge and some adjustments on master branch the mod dont load due some error with bob´s library.

**Comment by Nexela** [comment]
Will look at this as soon as i can.  Probably later tonight

On Feb 26, 2017 6:21 AM, "pyanodon" <notifications@github.com> wrote:

Hello, after the merge and some adjustments on master branch the mod dont
load due some error with bob´s library.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pyanodon/pYCoalprocesing/issues/23>, or mute the thread

**Comment by Nexela** [comment]
If it is any easier I can typically be found on Discord as Nexela#9467.

My guess is you made some weird changes without pulling in changes first.

The easiest way to figure it out would be for you to save as a new branch and push it up so I can see what the differences are.

**Comment by Nexela** [comment]
Booboo found and fixed
