### ISSUE TITLE
PIPES - Gasifier

### ISSUE THREAD

**Issue by Nexela** [pyanodon/pYCoalprocesing#8]
Should be some fairly easy fixes just need to adjust offsets, add in pipe_pictures

**Comment by pyanodon** [comment]
I think this weekend will be the bugfix graphics weekend. XD

**Comment by pyanodon** [comment]
Tired to make gasifier similar to the powerhouse file structure, but the game return an error i never heard:

"wrong argument count of vector" 

Happens when i try to add the custom pipe connections. I uploaded anyway, dunno what to do. After solve that, i will copy the same structure for the older buildings which still in the old file structure.

**Comment by Nexela** [comment]
I believe it is related to a change I made to Proto.pipes. Looking into it right now

**Comment by Nexela** [comment]
Found your typo.
gasifier.lua line 81
pipe_connections = {{ type="input", position = {-4,5, -0.5} }}

P.S git keeps all your backups so you don't have to worry about creating .old files
In git desktop I believe you can click on the file and checkout the last committed version to go back.

**Comment by Nexela** [comment]
As long as you get the pipe endings cleaned up in the image I can go through this weekend and add in the pipe connections

**Comment by pyanodon** [comment]
I cleaned the images. :)

**Comment by Nexela** [comment]
Nice, will be pushing a batch of code cleanup updates here in a minute too

**Comment by pyanodon** [comment]
Is midnight here
 Tomorrow i will take a nice look on it. :) great job so far
